# Streamlit Cloud Secrets Configuration
# Copy this content to your Streamlit Cloud app's Secrets section

# =============================================================================
# DATABASE CONFIGURATION (REQUIRED)
# Replace with your actual Supabase connection details
# =============================================================================

# Main database URL - replace with your Supabase PostgreSQL URL
DATABASE_URL = "postgresql://postgres.YOUR_USER_ID:YOUR_PASSWORD@YOUR_HOST.supabase.co:6543/postgres"

# Individual PostgreSQL connection parameters
PGDATABASE = "postgres"
PGHOST = "YOUR_HOST.supabase.co"
PGPORT = "6543"
PGUSER = "postgres.YOUR_USER_ID"
PGPASSWORD = "YOUR_PASSWORD"

# =============================================================================
# EXAMPLE WITH SAMPLE VALUES (replace with your actual values)
# =============================================================================
# DATABASE_URL = "postgresql://postgres.abcdefghijklmnop:MySecurePassword123@aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres"
# PGDATABASE = "postgres"
# PGHOST = "aws-0-ap-southeast-1.pooler.supabase.com"
# PGPORT = "6543"
# PGUSER = "postgres.abcdefghijklmnop"
# PGPASSWORD = "MySecurePassword123"

# =============================================================================
# OPTIONAL SERVICES (only add if you need these features)
# =============================================================================

# Google OAuth for backup features (optional)
# GOOGLE_CLIENT_ID = "your-google-client-id.apps.googleusercontent.com"
# GOOGLE_CLIENT_SECRET = "your-google-client-secret"

# SendGrid for email notifications (optional)
# SENDGRID_API_KEY = "SG.your-sendgrid-api-key"

# Twilio for SMS notifications (optional)
# TWILIO_ACCOUNT_SID = "ACyour-twilio-account-sid"
# TWILIO_AUTH_TOKEN = "your-twilio-auth-token"
# TWILIO_PHONE_NUMBER = "+1234567890"

# =============================================================================
# HOW TO USE THIS FILE:
# =============================================================================
# 1. Get your Supabase connection details from Settings → Database
# 2. Replace YOUR_USER_ID, YOUR_PASSWORD, YOUR_HOST with actual values
# 3. Copy the entire content (uncommented lines)
# 4. Paste in Streamlit Cloud → App Settings → Secrets
# 5. Save and wait for automatic redeployment
# =============================================================================